export { default as Map } from "./home/Map.vue"
export { default as Timer } from "./home/Timer.vue"
export { default as ViewEcts } from "./home/ViewEcts.vue"
export { default as PopupTicket } from "./home/PopupTicket.vue"
export { default as PopupLogin } from "./home/PopupLogin.vue"
export { default as DialButton } from "./home/DialButton.vue"
export { default as Timeline } from "./home/Timeline.vue"
export { default as QRReader } from "./home/QRReader.vue"
export { default as PopupLottery } from "./home/PopupLottery.vue"

