/**
 * Try IT! API
 * Official API for the Try IT! congress
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maximo.garcia.martinez@alumnos.upm.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DateResource } from "./date"
import { PrizeResource } from "./prize"
import { SpeakerResource } from "./speaker"

export interface TalkResource {
	title: string
	id: number
	description?: string
	url?: string
	video?: string
	startDate: DateResource
	endDate: DateResource
	slide?: string
	room?: string
	prize?: PrizeResource | null
	speakers?: Array<SpeakerResource>
}
