/**
 * Try IT! API
 * Official API for the Try IT! congress
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maximo.garcia.martinez@alumnos.upm.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TicketResource {
	name: string
	lastname: string
	identity: string
	email: string
	isStudent: boolean
	isUpmStudent?: boolean
	upmSchool?: string
	degree?: string
	year?: number
	phone: string
	toPrint: boolean
}
