import { routes } from "~/routes"

/*
 * DESCRIPTION
 * It checks that the path is a valid construction of the path
 * EXAMPLES
 * compareUrl("/", "/") => true
 * compareUrl("/home", "/home") => true
 * compareUrl("/error", "/") => false
 * compareUrl("/event/12312", "/event/:id") => true
 * compareUrl("/event/12312/error", "/event/:id") => false
 * compareUrl("/event/12312/error", "/event/:id/error") => true
 * compareUrl("/event", "/event/:id") => false
 */
function compareUrl(currentUrl: string, path: string): boolean {
	const currentUrlArr = currentUrl.split("/").filter(e => e !== "")
	const pathArr = path.split("/").filter(e => e !== "")
	if (currentUrlArr.length !== pathArr.length) {
		return false
	}
	pathArr.forEach((_, i) => {
		if (pathArr[i].charAt(0) === ":") {
			pathArr[i] = ".+"
		}
	})
	const re = new RegExp(`^\\/${pathArr.join("\\/")}$`)
	const result = re.exec(currentUrl)
	return result !== null
}

/*
 * WHY
 * Nuxt generates routes automatically. It doesn't allow you to create your own routes.
 * This pages has some routes that needs to be disabled depending on the time of the year (in August you shouldn't be able to get a ticket, for example)
 * The way of solving this problem is with this middleware. We have a routing array, where we have a boolean for each path and we select which one we want to
 * enable and which ones not. This allows us in the future to send that array via API so we don't need to modify the frontend at all.
 *
 * DESCRIPTION
 * This function takes the current path of the browser and then checks if the path is supposed to be visible for the user. For that it checks the routes array.
 *
 * NOTE: If the path is not in the automatic routes array generated by nuxt, then it will load automatically notFound page (see nuxt.config.ts)
 *
 */
export default function({ ssrContext, store, redirect }: any) {
	const currentUrl = ssrContext.url

	// First we check that the route is correct. This is made to remove /event from a valid route
	// (generated by nuxt because we have the folder event inside the page)
	const isCorrect = routes.map(r => compareUrl(currentUrl, r.path))
	if (!isCorrect.some(e => e)) {
		redirect("/not-found")
	}

	const canBeVisible = routes.find(r => r.can_be_shown)
	if (!canBeVisible && canBeVisible !== undefined) {
		redirect("/not-visible")
	}
}
